::  urui: shared UI contract.
::
::  The whole public surface of the urui shell, as data.  A consuming
::  application builds one $shell-spec and one $app-config; urui builds
::  the page, the css, and the browser runtime from those.
::
::  urui never imports a consumer's /sur and never names a consumer.
::  The dependency direction is strictly consumer -> urui.
::
|%
::
+$  app-id
  ::  Identity and namespace of the consuming application.
  ::
  ::  Example:
  ::    [%sample 'Sample' '/apps/sample' 'sample.session.v1' 1]
  $:  name=@tas
      title=@t
      base=@t
      storage-key=@t
      storage-version=@ud
  ==
::
+$  doc-kind
  ::  One class of document the application edits or displays.
  ::
  ::  `leaf` is the clay extension the document is stored under; `ext`
  ::  is the suffix a tab label shows.  They differ whenever a mark is
  ::  reused for a format that names itself differently — DOT stored as
  ::  `%txt` and labelled `.dot` is the case that forced the split.
  ::  `tabs` asks for a document tab strip, `refs` for the Add Ref control.
  $:  name=@tas
      label=@t
      untitled=@t
      ext=@ta
      leaf=@ta
      mime=@t
      tabs=?
      refs=?
  ==
::
+$  pane-role  ?(%reference %editor %result)
::
+$  pane-mode
  ::  %read-only forbids the `+` control, tab close, dirty marks, and
  ::  every file-write path into the pane, whatever a band declares.
  ::
  ::  It does not forbid document tabs: a read-only pane may carry a
  ::  %documents or %views level and show an imported copy of anything
  ::  the editor pane can open.
  ?(%read-only %read-write)
::
+$  reveal
  ::  Whether the user may hide a band, and where that choice persists.
  ::
  ::  `key` is a field of the urui-owned `paneBands` session record; ~
  ::  pins the band open and renders no toggle.  `label` names the
  ::  toggle for assistive technology.
  $:  key=(unit @t)
      open=?
      label=@t
  ==
::
+$  tab-source
  ::  Where one level's tabs come from.
  ::
  ::  %views      the explorer strip: `fixed` seeds it and the runtime
  ::              appends documentation tabs and one reference tab per
  ::              imported document, for every $doc-kind with refs=&
  ::  %documents  the $doc-kind tab store -- clay-backed, persisted
  ::  %fixed      exactly `fixed`, for the life of the page
  ::  %dynamic    replaced wholesale by `runtime.panes.set`
  $?  %views  %documents  %fixed  %dynamic  ==
::
+$  tab-level
  ::  One depth of tabs inside a pane, outermost first.
  ::
  ::  The strip's element id is `{pane-id}-{name}-tabs`.  Depth 0 is
  ::  emitted by urui-shell; deeper strips are generated by the runtime,
  ::  once per open parent tab.  `add=~` renders no `+` control.
  $:  name=@tas
      label=@t
      source=tab-source
      kind=(unit @tas)
      fixed=(list [name=@tas label=@t])
      add=(unit @t)
      close=?
      reorder=?
  ==
::
+$  band-item
  ::  %label    one line of text, nothing else
  ::  %heading  title, status span, and right-justified actions
  ::  %controls consumer marl, laid out as one row
  ::  %tabs     the tab strips, outermost level first
  ::  %panel    the tab panel: an optional Ace host plus consumer marl
  $%  [%label text=@t]
      [%heading title=(unit @t) status-id=(unit @t) actions=marl]
      [%controls =marl]
      [%tabs levels=(list tab-level)]
      [%panel id=@t host=(unit editor) body=marl]
  ==
::
+$  band
  ::  One horizontal sub-pane, rendered in the order given.
  ::
  ::  Band order is the whole layout language: a %heading before the
  ::  %tabs band is a heading above the tabs, after it is a heading
  ::  below them.  `name` is the band's id fragment, `{pane-id}-{name}`.
  $:  name=@tas
      =reveal
      item=band-item
  ==
::
+$  pane
  ::  One UI region: a mode and the bands stacked inside it.
  ::
  ::  Exactly one band is %tabs and exactly one is %panel; tab levels
  ::  below depth 0 are nested inside the panel by the runtime, not
  ::  declared as further bands.
  $:  role=pane-role
      id=@t
      label=@t
      mode=pane-mode
      kind=(unit @tas)
      bands=(list band)
  ==
::
+$  editor
  ::  An Ace host managed by urui.
  ::
  $:  id=@t
      label=@t
      mode=@t
      wrap=?
      read-only=?
      max-bytes=@ud
  ==
::
+$  ace-spec
  ::  Vendored Ace runtime parameters.
  ::
  ::  `global` is the window property the loader publishes, kept
  ::  consumer-named so an adopting application need not rename it.
  $:  base=@t
      global=@t
      version=@t
      mode=@t
      light=@t
      dark=@t
      exts=(list @t)  ::  Full module ids, e.g. 'ace/ext/searchbox'.
      use-worker=?
  ==
::
+$  transport  ?(%header %body)
::
+$  endpoints
  ::  The four file operations and how the path travels.
  ::
  ::  %header sends the clay path in `path-header`; %body sends it as a
  ::  json object with `path` segments, `source` text, and `overwrite`.
  ::  `{kind}` in a route is replaced by the $doc-kind name.
  $:  =transport
      path-header=(unit @t)
      flag-header=(unit @t)
      browse=@t
      load=@t
      save=@t
      delete=@t
  ==
::
+$  slot
  ::  One persisted field of the session record.
  ::
  ::  `key` is the json key as it already appears on disk, so an
  ::  existing record keeps loading without migration.
  $:  key=@t
      owner=?(%urui %app)
      shape=?(%tabs %active %next %scalar %record)
      kind=(unit @tas)
  ==
::
+$  shortcut
  ::  An application chord urui dispatches on the app's behalf.
  ::
  ::  %editor/%no-editor test Ace focus; %preview uses the consumer
  ::  runtime option `shortcuts.preview`, even while Ace has focus.
  ::  Register command handlers through `runtime.shortcuts.register`.
  ::
  $:  binding=@t
      command=@t
      when=?(%always %preview %editor %no-editor)
  ==
::
+$  limits
  ::  Numeric policy, in milliseconds, pixels, percent, and bytes.
  ::
  $:  render-debounce=@ud
      save-debounce=@ud
      min-explorer=@ud
      divider=@ud
      pane-min=@ud
      pane-max=@ud
      narrow=@ud
      max-source=@ud
  ==
::
+$  app-config
  ::  Everything the browser runtime needs, as data.
  ::
  ::  Emitted to the page as one json object; nothing in urui's
  ::  javascript reads a consumer name except through this record.
  ::
  $:  =app-id
      kinds=(list doc-kind)
      =endpoints
      =limits
      slots=(list slot)
      shortcuts=(list shortcut)
      statuses=(list [@tas @t])
      docs-root=(unit @t)
      share-param=(unit [name=@t max=@ud param-max=@ud])
      =ace-spec
  ==
::
+$  shell-spec
  ::  Everything the Sail frame needs.
  ::
  ::  `brand`, `toolbar`, `help`, and `dialogs` are consumer marl slots;
  ::  `scripts` and `styles` are emitted in the order given.
  $:  =app-config
      brand=marl
      toolbar=marl
      panes=[reference=pane editor=pane result=pane]
      help=marl
      dialogs=marl
      styles=(list @t)
      scripts=(list @t)
  ==
--
