::  urui: shared UI contract.
::
::  The whole public surface of the urui shell, as data.  A consuming
::  application builds one $shell-spec and one $app-config; urui builds
::  the page, the css, and the browser runtime from those.
::
::  urui never imports a consumer's /sur and never names a consumer.
::  The dependency direction is strictly consumer -> urui.
::
|%
::
+$  app-id
  ::  Identity and namespace of the consuming application.
  ::
  ::  Example:
  ::    [%sample 'Sample' '/apps/sample' 'sample.session.v1' 1]
  $:  name=@tas
      title=@t
      base=@t
      storage-key=@t
      storage-version=@ud
  ==
::
+$  pane-role  ?(%reference %editor %result)
::
+$  pane-mode
  ::  %read-only forbids the `+` control, tab close, dirty marks, every
  ::  file-write path into the pane, and every edit to a store bound
  ::  there (drafts included), whatever a band declares.
  ::
  ::  It does not forbid document tabs: a read-only pane may carry a
  ::  %documents or %views level and show an imported copy of anything
  ::  the editor pane can open.
  ?(%read-only %read-write)
::
+$  reveal
  ::  Whether the user may hide a band, and where that choice persists.
  ::
  ::  `key` is a field of the urui-owned `paneBands` session record; ~
  ::  pins the band open and renders no toggle.  `label` names the
  ::  toggle for assistive technology.
  $:  key=(unit @t)
      open=?
      label=@t
  ==
::
+$  tab-source
  ::  Where one level's tabs come from.
  ::
  ::  %views      the explorer strip: `fixed` seeds it and the runtime
  ::              appends documentation tabs and reference tabs
  ::  %documents  the $store its `kind` names -- clay-backed, persisted
  ::  %fixed      exactly `fixed`, for the life of the page
  ::  %dynamic    replaced wholesale by `runtime.panes.set`
  $?  %views  %documents  %fixed  %dynamic  ==
::
+$  tab-level
  ::  One depth of tabs inside a pane, outermost first.
  ::
  ::  The strip's element id is `{pane-id}-{name}-tabs`.  Depth 0 is
  ::  emitted by urui-shell; deeper strips are generated by the runtime,
  ::  once per open parent tab.  `add=~` renders no `+` control.
  $:  name=@tas
      label=@t
      source=tab-source
      kind=(unit @tas)
      fixed=(list [name=@tas label=@t])
      add=(unit @t)
      close=?
      reorder=?
  ==
::
+$  band-item
  ::  %label    one line of text, nothing else
  ::  %heading  title, status span, and right-justified actions
  ::  %controls consumer marl, laid out as one row
  ::  %tabs     the tab strips, outermost level first
  ::  %panel    the tab panel: an optional Ace host plus consumer marl
  $%  [%label text=@t]
      [%heading title=(unit @t) status-id=(unit @t) actions=marl]
      [%controls =marl]
      [%tabs levels=(list tab-level)]
      [%panel id=@t host=(unit editor) body=marl]
  ==
::
+$  band
  ::  One horizontal sub-pane, rendered in the order given.
  ::
  ::  Band order is the whole layout language: a %heading before the
  ::  %tabs band is a heading above the tabs, after it is a heading
  ::  below them.  `name` is the band's id fragment, `{pane-id}-{name}`.
  $:  name=@tas
      =reveal
      item=band-item
  ==
::
+$  pane
  ::  One UI region: a mode and the bands stacked inside it.
  ::
  ::  Exactly one band is %tabs and exactly one is %panel; tab levels
  ::  below depth 0 are nested inside the panel by the runtime, not
  ::  declared as further bands.
  $:  role=pane-role
      id=@t
      label=@t
      mode=pane-mode
      kind=(unit @tas)
      bands=(list band)
  ==
::
+$  editor
  ::  An Ace host managed by urui.  Ace always wraps; a store's editor
  ::  is read-only where its pane is %read-only or its root has no save.
  ::
  $:  id=@t
      label=@t
      mode=@t
  ==
::
+$  ace-spec
  ::  Vendored Ace runtime parameters.
  ::
  ::  `global` is the window property the loader publishes, kept
  ::  consumer-named so an adopting application need not rename it.
  $:  base=@t
      global=@t
      version=@t
      mode=@t
      light=@t
      dark=@t
      exts=(list @t)  ::  Full module ids, e.g. 'ace/ext/searchbox'.
      use-worker=?
  ==
::
+$  slot
  ::  One persisted field of the session record.
  ::
  ::  `key` is the json key as it already appears on disk, so an
  ::  existing record keeps loading without migration.
  $:  key=@t
      owner=?(%urui %app)
      shape=?(%tabs %active %next %scalar %record)
      kind=(unit @tas)
  ==
::
+$  shortcut
  ::  An application chord urui dispatches on the app's behalf.
  ::
  ::  %editor/%no-editor test Ace focus; %preview uses the consumer
  ::  runtime option `shortcuts.preview`, even while Ace has focus.
  ::  Register command handlers through `runtime.shortcuts.register`.
  ::
  $:  binding=@t
      command=@t
      when=?(%always %preview %editor %no-editor)
  ==
::
+$  limits
  ::  Numeric policy, in milliseconds, pixels, percent, and bytes.
  ::
  $:  render-debounce=@ud
      save-debounce=@ud
      min-explorer=@ud
      divider=@ud
      pane-min=@ud
      pane-max=@ud
      max-source=@ud
  ==
::
+$  screen-format
  ::  %columns: reference, editor, and result side by side.  %rows:
  ::  reference beside editor stacked over result.
  $~(%columns ?(%columns %rows))
::
+$  root
  ::  One place a store's files live, under the app's file root.
  ::
  ::  `scope` is ~ for the file root itself.  A save path without an
  ::  allowed mark as its last segment gets the first mark appended.
  ::  `ext` is the extension labels show; ~ shows the mark.  `save`
  ::  is | for a root only the app writes, through +write:urui-files.
  $:  scope=path
      marks=(list @tas)
      ext=(unit @tas)
      save=?
  ==
::
+$  action  ?(%open %save %save-as %copy %ref %browse)
::
+$  store
  ::  One document tab store, rendered by one %documents tab level.
  ::
  ::  Its editor is the Ace host of the %panel band in the same pane.
  ::  `preview` asks for a preview host beside it, and is the display
  ::  a new tab starts in.
  $:  name=@tas
      noun=@t
      untitled=@t
      starter=@t
      roots=(list root)
      preview=(unit ?(%source %preview))
      actions=(list action)
      refs=?
      share=(unit [param=@t max=@ud param-max=@ud])
  ==
::
+$  tree
  ::  One explorer file tree, the panel of one %views tab.
  ::
  ::  `scopes` selects the store roots shown; ~ shows them all.
  $:  view=@tas
      store=@tas
      scopes=(list path)
  ==
::
+$  files
  ::  The document and file module.  `url` is the one POST route of the
  ::  json file wire, which the app's agent serves with urui-files.
  $:  url=@t
      stores=(list store)
      trees=(list tree)
  ==
::
+$  app-config
  ::  Everything the browser runtime needs, as data.
  ::
  ::  Emitted to the page as one json object; nothing in urui's
  ::  javascript reads a consumer name except through this record.
  ::
  ::  `layout` is the screen format a session starts in; the user's
  ::  saved choice overrides it.  `collapse` gives the result pane a
  ::  collapse control in its %heading band; it bunts to off, so a
  ::  config built by `%*` over a bunt does not opt in by accident.
  ::
  ::  `files` turns on urui's document and file module; ~ leaves it off.
  ::  A %documents tab level's `kind` names one of its stores.
  ::
  $:  =app-id
      =limits
      slots=(list slot)
      shortcuts=(list shortcut)
      statuses=(list [@tas @t])
      docs-root=(unit @t)
      =ace-spec
      layout=screen-format
      collapse=$~(| ?)
      files=(unit files)
  ==
::
+$  shell-spec
  ::  Everything the Sail frame needs.
  ::
  ::  `brand`, `toolbar`, `help`, and `dialogs` are consumer marl slots;
  ::  `scripts` and `styles` are emitted in the order given.  `head` is
  ::  consumer marl appended to <head>, after the styles: a favicon,
  ::  meta tags.
  ::
  ::  Without a %views level on the reference pane the frame is compact
  ::  and presentation only: `files` must be ~, or ++build crashes.
  $:  =app-config
      brand=marl
      toolbar=marl
      panes=[reference=pane editor=pane result=pane]
      help=marl
      dialogs=marl
      styles=(list @t)
      scripts=(list @t)
      head=marl
  ==
--
